### ISSUE TITLE
Unsolved reference in  NetworkManager.kt

### ISSUE THREAD

**Issue by OG0mez** [amilcar-sr/paging#1]

**Comment by amilcar-sr** [comment]
Is this because of **PrivateConstants.API_KEY** in NetworkManager? or you mean other dependency? Please provide more details 🙏🏻

**Comment by OG0mez** [comment]
I get an unsolved reference here 
`val url = request.url().newBuilder().addQueryParameter(API_KEY_PARAM, **PrivateConstants**.API_KEY).build()`
had to change to 

`val url = request.url().newBuilder().addQueryParameter("api_key", API_KEY_PARAM).build()`
sorry for the vague response i made a mistake and send the issue before finishing editing 😅

**Comment by amilcar-sr** [comment]
@OG0mez that won't work, please check the readme of the project. I placed instructions in [the second paragraph](https://github.com/amilcar-sr/paging#%EF%B8%8F-api-key-very-important) 🙂
